stations = [
    {
        "id": 1,
        "status": 0,
        "isVip": 1,
        "name": "VIP_1",
        "pricePerHour": "35",
        "discount": 0,
    },
    {
        "id": 2,
        "status": 0,
        "isVip": 1,
        "name": "VIP_2",
        "pricePerHour": "35",
        "discount": 0,
    },
    {
        "id": 3,
        "status": 0,
        "isVip": 0,
        "name": "PS5_1",
        "pricePerHour": "25",
        "discount": 0,
    },
    {
        "id": 4,
        "status": 0,
        "isVip": 0,
        "name": "PS5_2",
        "pricePerHour": "25",
        "discount": 0,
    },
    {
        "id": 5,
        "status": 0,
        "isVip": 0,
        "name": "PS4_1",
        "pricePerHour": "20",
        "discount": 0,
    },
    {
        "id": 6,
        "status": 0,
        "isVip": 0,
        "name": "PS4_2",
        "pricePerHour": "20",
        "discount": 0,
    },
    {
        "id": 7,
        "status": 0,
        "isVip": 0,
        "name": "PS4_3",
        "pricePerHour": "20",
        "discount": 0,
    },
    {
        "id": 8,
        "status": 0,
        "isVip": 0,
        "name": "PS4_4",
        "pricePerHour": "20",
        "discount": 0,
    },
    {
        "id": 9,
        "status": 0,
        "isVip": 0,
        "name": "PS4_5",
        "pricePerHour": "20",
        "discount": 0,
    },
    {
        "id": 10,
        "status": 0,
        "isVip": 0,
        "name": "PS4_6",
        "pricePerHour": "20",
        "discount": 0,
    }    
]